"""Crystal data loading and batching.

Loads pre-processed crystal tensors and batches them with PyTorch Geometric:

- ``CrystalDataset`` loads pre-processed data and converts each crystal into a
  PyG ``Data`` object (missing attributes are returned as empty tensors so the
  batch structure stays uniform).
- ``CrystalDataModule`` is a PyTorch Lightning wrapper for training/eval.
- ``collate_fn`` handles PyG batching with offset logic for ring/molecule indices.
"""

import os
import torch
try:  # Lightning is only needed for CrystalDataModule (training/eval), not CrystalDataset.
    import pytorch_lightning as pl
    _LightningDataModule = pl.LightningDataModule
except ModuleNotFoundError:  # allow inference/plotting without pytorch-lightning installed
    pl = None
    _LightningDataModule = object
from torch.utils.data import Dataset, DataLoader
from torch_geometric.data import Data, Batch
from typing import List, Dict, Any, Optional, Union
import pickle
import numpy as np
from packflow.utils.crystal_utils import lattice_matrix_to_k_basis

class CrystalDataset(Dataset):
    """
    A PyTorch Dataset for loading pre-processed crystal structure data.

    This dataset loads data from .pt files generated by final_crystal_processor.py,
    and formats each crystal structure into a torch_geometric.data.Data object.
    """
    
    def __init__(self, processed_data_path: str, max_samples: Optional[int] = None, refcode_filter: Optional[List[str]] = None):
        """
        Args:
            processed_data_path (str): Path to the processed .pt file containing a list of crystal data dictionaries.
            max_samples (int, optional): Maximum number of samples to load. If None, loads all data.
            refcode_filter (List[str], optional): List of refcodes to include. If None, loads all data.
        """
        super().__init__()
        if not os.path.exists(processed_data_path):
            raise FileNotFoundError(f"Processed data file not found at: {processed_data_path}")
        
        print(f"Loading crystal data from: {processed_data_path}")
        
        # Load the data - handle both .pt and .pkl files
        if processed_data_path.endswith('.pt'):
            self.cached_data = torch.load(processed_data_path, map_location='cpu')
        elif processed_data_path.endswith('.pkl'):
            with open(processed_data_path, 'rb') as f:
                self.cached_data = pickle.load(f)
        else:
            # Try to load as torch file first, then pickle
            try:
                self.cached_data = torch.load(processed_data_path, map_location='cpu')
            except:
                with open(processed_data_path, 'rb') as f:
                    self.cached_data = pickle.load(f)
        
        # Filter out any failed processing results (dictionaries with 'error' key)
        if isinstance(self.cached_data, list):
            self.cached_data = [item for item in self.cached_data if not isinstance(item, dict) or 'error' not in item]
        
        # Filter by refcodes if specified
        if refcode_filter is not None:
            refcode_set = set(refcode_filter)
            original_count = len(self.cached_data)
            self.cached_data = [item for item in self.cached_data if item.get('refcode') in refcode_set]
            print(f"Filtered dataset by refcodes: {original_count} -> {len(self.cached_data)} samples")
            print(f"  Refcodes requested: {refcode_filter}")
            found_refcodes = [item.get('refcode') for item in self.cached_data]
            print(f"  Refcodes found: {found_refcodes}")
        
        # Limit the number of samples if specified
        if max_samples is not None and len(self.cached_data) > max_samples:
            self.cached_data = self.cached_data[:max_samples]
            print(f"Limited dataset to {max_samples} samples")
        
        print(f"Successfully loaded {len(self.cached_data)} valid crystal structures")

    def __len__(self) -> int:
        """Returns the total number of crystals in the dataset."""
        return len(self.cached_data)

    def __getitem__(self, index: int) -> Data:
        """
        Retrieves a single crystal data point and converts it into a PyG Data object.

        Args:
            index (int): The index of the data point to retrieve.

        Returns:
            torch_geometric.data.Data: A PyG Data object representing the crystal.
        """
        data_dict = self.cached_data[index]
        
        # Helper function to safely convert to tensor
        def safe_tensor_conversion(data, dtype=None, default_shape=None):
            """Safely convert data to tensor with error handling."""
            if data is None:
                if default_shape is not None:
                    return torch.zeros(default_shape, dtype=dtype or torch.float32)
                return torch.tensor([])
            
            if torch.is_tensor(data):
                if dtype is not None:
                    return data.to(dtype)
                return data
            
            if isinstance(data, (list, tuple)):
                data = np.array(data)
            
            if isinstance(data, np.ndarray):
                tensor = torch.from_numpy(data)
                if dtype is not None:
                    tensor = tensor.to(dtype)
                return tensor
            
            # Handle scalar values
            if np.isscalar(data):
                return torch.tensor([data], dtype=dtype or torch.float32)
            
            return torch.tensor(data, dtype=dtype or torch.float32)

        try:
            # Essential graph structure - these are required
            edge_index = safe_tensor_conversion(data_dict.get('edge_index'), torch.long, default_shape=(2, 0))
            atom_types = safe_tensor_conversion(data_dict.get('atom_types'), torch.long, default_shape=(0,))
            
            # Determine number of nodes from atom_types
            num_nodes = atom_types.shape[0] if len(atom_types.shape) > 0 and atom_types.shape[0] > 0 else 0
            
            # Node and bond features
            node_features = data_dict.get('node_features', None)
            bond_features = data_dict.get('bond_features', None)

            # Edge attributes (prefer existing edge_attr, else fall back to bond_features)
            edge_attr = data_dict.get('edge_attr', None)
            if edge_attr is None and bond_features is not None:
                edge_attr = bond_features
            edge_attr = safe_tensor_conversion(edge_attr)  # keep original dtype
            
            # Essential lattice information for crystal ML models
            lattice_1 = safe_tensor_conversion(data_dict.get('lattice_1'), torch.float32)  # (6,) - a,b,c,alpha,beta,gamma
            cell_1 = safe_tensor_conversion(data_dict.get('cell_1'), torch.float32)        # (3,3) - lattice matrix
            
            # k-basis representation (O(3)-invariant)
            k_basis = data_dict.get('k_basis', None)
            if k_basis is not None:
                k_basis = safe_tensor_conversion(k_basis, torch.float32)  # (6,) - k-basis coefficients
            else:
                # Compute k-basis from cell_1 if not present (fallback for older data)
                if cell_1.numel() > 0 and cell_1.shape == (3, 3):
                    cell_1_np = cell_1.cpu().numpy()
                    k_basis_np = lattice_matrix_to_k_basis(cell_1_np)
                    k_basis = torch.from_numpy(k_basis_np).float()
                else:
                    k_basis = torch.zeros(6, dtype=torch.float32)  # Default fallback
            
            # Fractional coordinates for flow matching models
            frac_coords = safe_tensor_conversion(data_dict.get('frac_coords'), torch.float32, (num_nodes, 3))
            
            # Whole cartesian coordinates for cartesian flow matching models
            whole_cartesian_coords = safe_tensor_conversion(data_dict.get('whole_cartesian_coords'), torch.float32, (num_nodes, 3))
            
            # Essential molecule identification
            molecule_ids = safe_tensor_conversion(data_dict.get('molecule_ids'), torch.long, (num_nodes,))
            
            # Hydrogen bonding masks (optional - only present when tag_hydrogen_bonding=True and removeHs=True)
            hbond_donor_mask = safe_tensor_conversion(data_dict.get('hbond_donor_mask'), torch.bool, (num_nodes,))
            hbond_acceptor_mask = safe_tensor_conversion(data_dict.get('hbond_acceptor_mask'), torch.bool, (num_nodes,))
            
            # Ring fields are always tensors (empty if missing) so collation stays uniform.
            ring_atom_pairs = safe_tensor_conversion(data_dict.get('ring_atom_pairs'), torch.long, default_shape=(0, 2))
            ring_centroids = safe_tensor_conversion(data_dict.get('ring_centroids'), torch.float32, default_shape=(0, 3))
            ring_molecule_ids = safe_tensor_conversion(data_dict.get('ring_molecule_ids'), torch.long, default_shape=(0,))
            ring_sizes = safe_tensor_conversion(data_dict.get('ring_sizes'), torch.long, default_shape=(0,))
            num_rings = data_dict.get('num_rings', 0)
            
            # For each molecule_id, assign 0..(count-1) to its atoms in original order.
            if molecule_ids.numel() == 0:
                atom_idx_in_mol = torch.arange(num_nodes, dtype=torch.long)
            else:
                mi = molecule_ids
                N = mi.numel()

                # stable sort by molecule id
                perm = torch.argsort(mi, stable=True)
                mi_sorted = mi[perm]

                # group starts in sorted array
                new_group = torch.ones(N, dtype=torch.bool)
                if N > 1:
                    new_group[1:] = mi_sorted[1:] != mi_sorted[:-1]

                # group id per position in sorted space
                grp_id_sorted = torch.cumsum(new_group, dim=0) - 1  # 0..G-1

                # first position of each group in sorted space
                first_pos_sorted = torch.nonzero(new_group, as_tuple=False).squeeze(1)

                # rank within group in sorted space: idx - first_pos_of_its_group
                rank_sorted = torch.arange(N) - first_pos_sorted[grp_id_sorted]

                # invert the sort to map ranks back to original atom order
                invperm = torch.empty(N, dtype=torch.long)
                invperm[perm] = torch.arange(N)
                atom_idx_in_mol = rank_sorted[invperm].to(torch.long)
            
            # Create the PyG Data object with only essential features
            data = Data(
                num_nodes=num_nodes,
                
                # Essential graph structure
                edge_index=edge_index,
                atom_types=atom_types,
                edge_attr=edge_attr,  # Re-included for potential ML model use
                
                # Essential lattice information for crystal ML models
                lattice_1=lattice_1,  # Lattice parameters (a, b, c, alpha, beta, gamma)
                cell_1=cell_1,        # 3x3 lattice matrix for coordinate transformations
                k_basis=k_basis,      # O(3)-invariant k-basis representation (6 coefficients)
                
                # Fractional coordinates for flow matching
                frac_coords=frac_coords,  # Fractional coordinates for flow matching
                
                # Whole cartesian coordinates for cartesian flow matching models
                whole_cartesian_coords=whole_cartesian_coords,  # Whole cartesian coordinates for cartesian flow matching
                
                # Essential molecule identification
                molecule_ids=molecule_ids,
                atom_idx_in_mol=atom_idx_in_mol,
                
                # Hydrogen bonding masks (optional - only present when tag_hydrogen_bonding=True and removeHs=True)
                hbond_donor_mask=hbond_donor_mask,
                hbond_acceptor_mask=hbond_acceptor_mask,
                
                # Rings are now guaranteed to be tensors (possibly empty)
                ring_atom_pairs=ring_atom_pairs,
                ring_centroids=ring_centroids,
                ring_molecule_ids=ring_molecule_ids,
                ring_sizes=ring_sizes,
                num_rings=num_rings,
                
                # Essential metadata
                refcode=data_dict.get('refcode', f'unknown_{index}'),
                smiles=data_dict.get('smiles', 'unknown')
            )
            
            # Attach optional node/bond features if provided
            if node_features is not None:
                data.node_features = safe_tensor_conversion(node_features)
            if bond_features is not None:
                data.bond_features = safe_tensor_conversion(bond_features)
            
            return data
            
        except Exception as e:
            print(f"Error processing data point {index} (refcode: {data_dict.get('refcode', 'unknown')}): {e}")
            # Return a minimal valid Data object in case of error
            return Data(
                num_nodes=1,
                edge_index=torch.zeros((2, 0), dtype=torch.long),
                atom_types=torch.tensor([1], dtype=torch.long),
                whole_cartesian_coords=torch.zeros((1, 3), dtype=torch.float32),
                refcode=data_dict.get('refcode', f'error_{index}'),
                smiles=data_dict.get('smiles', 'error')
            )


def collate_fn(data_list: List[Data]) -> Batch:
    """
    Custom collate function to batch a list of PyG Data objects.
    
    This function properly offsets molecule IDs and aromatic ring data when 
    batching multiple crystal structures.
    
    Args:
        data_list (List[Data]): A list of `torch_geometric.data.Data` objects.

    Returns:
        torch_geometric.data.Batch: A single batched graph object.
    """
    try:
        # Clean data objects for standard batching
        cleaned_data_list = []
        
        # Accumulators for manual ring batching
        ring_atom_pairs_list = []
        ring_centroids_list = []
        ring_molecule_ids_list = []
        ring_sizes_list = []
        ring_ptr = [0]
        
        ring_keys = {'ring_atom_pairs', 'ring_centroids', 'ring_molecule_ids', 'ring_sizes', 'num_rings'}

        # Pre-process loop: separate ring data from standard graph data
        for data in data_list:
            cleaned_data = Data()
            
            # 1. Copy standard attributes (excluding ring keys)
            # PyG Batch.from_data_list handles these automatically
            for key, value in data.items():
                if key not in ring_keys:
                    cleaned_data[key] = value
            
            cleaned_data_list.append(cleaned_data)
            
            # 2. Collect ring data for manual batching
            # Note: We can safely use getattr because __getitem__ now guarantees existence
            ring_atom_pairs = data.ring_atom_pairs
            ring_centroids = data.ring_centroids
            ring_molecule_ids = data.ring_molecule_ids
            ring_sizes = data.ring_sizes
            
            # Store only if non-empty, logic handles indices below
            if ring_atom_pairs.numel() > 0:
                ring_atom_pairs_list.append(ring_atom_pairs)
                ring_centroids_list.append(ring_centroids)
                ring_molecule_ids_list.append(ring_molecule_ids)
                ring_sizes_list.append(ring_sizes)
            else:
                # Append placeholders to maintain alignment for list indexing if needed,
                # though we use ring_ptr logic mostly.
                ring_atom_pairs_list.append(None)
                ring_centroids_list.append(None)
                ring_molecule_ids_list.append(None)
                ring_sizes_list.append(None)
        
        # 3. Batch the cleaned data (PyG handles standard keys)
        batch = Batch.from_data_list(cleaned_data_list)
        
        # 4. FIX: Adjust molecule_ids offsets
        max_molecule_id = []
        if hasattr(batch, 'molecule_ids') and batch.molecule_ids.numel() > 0:
            for data in data_list:
                if hasattr(data, 'molecule_ids') and data.molecule_ids.numel() > 0:
                    max_molecule_id.append(data.molecule_ids.max().item() + 1)
                else:
                    max_molecule_id.append(1)
            
            molecule_id_offset = 0
            start_idx = 0
            for i, data in enumerate(data_list):
                num_atoms = data.num_nodes
                end_idx = start_idx + num_atoms
                # Only offset if there are actual atoms
                if num_atoms > 0:
                    batch.molecule_ids[start_idx:end_idx] += molecule_id_offset
                molecule_id_offset += max_molecule_id[i]
                start_idx = end_idx
        else:
            # Initialize max_molecule_id even if no molecule_ids (for ring batching)
            for data in data_list:
                max_molecule_id.append(1)

        # 5. Manual Batching for Rings
        node_offset = 0
        ring_offset = 0
        
        final_ring_pairs = []
        final_ring_centroids = []
        final_ring_mol_ids = []
        final_ring_sizes = []
        
        for i, data in enumerate(data_list):
            pairs = ring_atom_pairs_list[i]
            
            if pairs is not None and pairs.numel() > 0:
                # Apply offsets
                pairs = pairs.clone()
                pairs[:, 1] += node_offset  # Offset atom indices
                pairs[:, 0] += ring_offset  # Offset ring IDs
                
                # Molecule ID offset for rings
                mol_offset = 0
                if i > 0:
                    mol_offset = sum(max_molecule_id[:i])
                
                mol_ids = ring_molecule_ids_list[i].clone()
                mol_ids += mol_offset
                
                final_ring_pairs.append(pairs)
                final_ring_centroids.append(ring_centroids_list[i])
                final_ring_mol_ids.append(mol_ids)
                final_ring_sizes.append(ring_sizes_list[i])
                
                curr_num_rings = len(ring_centroids_list[i])
                ring_offset += curr_num_rings
            
            node_offset += data.num_nodes
            ring_ptr.append(ring_offset)

        # Concatenate ring results
        if final_ring_pairs:
            batch.ring_atom_pairs = torch.cat(final_ring_pairs, dim=0)
            batch.ring_centroids = torch.cat(final_ring_centroids, dim=0)
            batch.ring_molecule_ids = torch.cat(final_ring_mol_ids, dim=0)
            batch.ring_sizes = torch.cat(final_ring_sizes, dim=0)
        else:
            batch.ring_atom_pairs = torch.empty((0, 2), dtype=torch.long)
            batch.ring_centroids = torch.empty((0, 3), dtype=torch.float32)
            batch.ring_molecule_ids = torch.empty((0,), dtype=torch.long)
            batch.ring_sizes = torch.empty((0,), dtype=torch.long)
            
        batch.ring_ptr = torch.tensor(ring_ptr, dtype=torch.long)
        
        return batch
        
    except Exception as e:
        print(f"Error in collate_fn: {e}")
        # Return a safe, minimal batch to prevent worker crash loop
        dummy_data = Data(num_nodes=1, edge_index=torch.zeros((2,0), dtype=torch.long))
        return Batch.from_data_list([dummy_data])


class CrystalDataModule(_LightningDataModule):
    """
    A PyTorch Lightning DataModule for crystal structure datasets.

    This DataModule handles the creation of datasets and dataloaders for
    training, validation, and testing, using standard PyG batching.
    """
    
    def __init__(
        self,
        train_path: Optional[str] = None,
        val_path: Optional[str] = None,
        test_path: Optional[str] = None,
        data_path: Optional[str] = None,
        train_split: float = 0.8,
        val_split: float = 0.1,
        batch_size: int = 32,
        num_workers: int = 4,
        max_samples: Optional[int] = None,
        shuffle_train: bool = True,
        pin_memory: bool = True,
        refcode_filter: Optional[List[str]] = None
    ):
        """
        Args:
            train_path (str, optional): Path to the training data (.pt file).
            val_path (str, optional): Path to the validation data (.pt file).
            test_path (str, optional): Path to the test data (.pt file).
            data_path (str, optional): Path to a single data file to split into train/val/test.
            train_split (float): Fraction of data to use for training (when using data_path).
            val_split (float): Fraction of data to use for validation (when using data_path).
            batch_size (int): The batch size for the dataloaders.
            num_workers (int): The number of worker processes for data loading.
            max_samples (int, optional): Maximum number of samples to load per split.
            shuffle_train (bool): Whether to shuffle the training data.
            pin_memory (bool): Whether to use pinned memory for faster GPU transfer.
            refcode_filter (List[str], optional): List of refcodes to include. If None, loads all data.
        """
        super().__init__()
        self.train_path = train_path
        self.val_path = val_path
        self.test_path = test_path
        self.data_path = data_path
        self.train_split = train_split
        self.val_split = val_split
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.max_samples = max_samples
        self.shuffle_train = shuffle_train
        self.pin_memory = pin_memory
        self.refcode_filter = refcode_filter
        
        # Validate input
        if not any([train_path, val_path, test_path, data_path]):
            raise ValueError("Must provide either individual split paths or a single data_path to split")

    def setup(self, stage: Optional[str] = None):
        """
        Creates the datasets for the specified stage ('fit', 'test', or None).
        
        Args:
            stage (str, optional): The stage for which to set up the data. 
                                   Can be 'fit' (for training/validation) or 'test'.
        """
        if self.data_path is not None:
            # Load single file and split
            self._setup_from_single_file(stage)
        else:
            # Load from separate files
            self._setup_from_separate_files(stage)

    def _setup_from_single_file(self, stage: Optional[str] = None):
        """Setup datasets by splitting a single data file."""
        print(f"Setting up datasets by splitting single file: {self.data_path}")
        
        # Load all data
        full_dataset = CrystalDataset(self.data_path, max_samples=self.max_samples)
        total_size = len(full_dataset)
        
        # Calculate split sizes
        train_size = int(self.train_split * total_size)
        val_size = int(self.val_split * total_size)
        test_size = total_size - train_size - val_size
        
        print(f"Splitting {total_size} samples into train({train_size}), val({val_size}), test({test_size})")
        
        # Create random split
        train_dataset, val_dataset, test_dataset = torch.utils.data.random_split(
            full_dataset, [train_size, val_size, test_size],
            generator=torch.Generator().manual_seed(42)  # For reproducible splits
        )
        
        if stage == 'fit' or stage is None:
            self.train_dataset = train_dataset
            self.val_dataset = val_dataset
        if stage == 'test' or stage is None:
            self.test_dataset = test_dataset

    def _setup_from_separate_files(self, stage: Optional[str] = None):
        """Setup datasets from separate train/val/test files."""
        if stage == 'fit' or stage is None:
            if self.train_path and os.path.exists(self.train_path):
                self.train_dataset = CrystalDataset(self.train_path, max_samples=self.max_samples, refcode_filter=self.refcode_filter)
                print(f"Loaded training dataset: {len(self.train_dataset)} samples")
            else:
                print(f"Warning: Training path not found or not provided: {self.train_path}")
                
            if self.val_path and os.path.exists(self.val_path):
                self.val_dataset = CrystalDataset(self.val_path, max_samples=self.max_samples, refcode_filter=self.refcode_filter)
                print(f"Loaded validation dataset: {len(self.val_dataset)} samples")
            else:
                print(f"Warning: Validation path not found or not provided: {self.val_path}")
                
        if stage == 'test' or stage is None:
            if self.test_path and os.path.exists(self.test_path):
                self.test_dataset = CrystalDataset(self.test_path, max_samples=self.max_samples, refcode_filter=self.refcode_filter)
                print(f"Loaded test dataset: {len(self.test_dataset)} samples")
            else:
                print(f"Warning: Test path not found or not provided: {self.test_path}")

    def train_dataloader(self) -> DataLoader:
        """Returns the DataLoader for the training set."""
        if not hasattr(self, 'train_dataset'):
            raise RuntimeError("Train dataset not setup. Call setup('fit') first.")
            
        return DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            shuffle=self.shuffle_train,
            num_workers=self.num_workers,
            collate_fn=collate_fn,
            pin_memory=self.pin_memory,
            persistent_workers=self.num_workers > 0
        )

    def val_dataloader(self) -> DataLoader:
        """Returns the DataLoader for the validation set."""
        if not hasattr(self, 'val_dataset'):
            raise RuntimeError("Validation dataset not setup. Call setup('fit') first.")
            
        return DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            collate_fn=collate_fn,
            pin_memory=self.pin_memory,
            persistent_workers=self.num_workers > 0
        )

    def test_dataloader(self) -> DataLoader:
        """Returns the DataLoader for the test set."""
        if not hasattr(self, 'test_dataset'):
            raise RuntimeError("Test dataset not setup. Call setup('test') first.")
            
        return DataLoader(
            self.test_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            collate_fn=collate_fn,
            pin_memory=self.pin_memory,
            persistent_workers=self.num_workers > 0
        )
